name: Python Package using Conda

on: 
  release:
    types: [created]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        pip install build
        pip install twine
    
    - name: Build
      run: |
        python -m build
        twine check dist/*    
    
    - name: Publish PyPI package
      env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_API_KEY }}
      run: |
        twine upload --repository-url=https://test.pypi.org/legacy/ dist/*
